name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy files to VM via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        port: 22
        script: |
          cd ~/CodeSync
          git pull || git clone https://github.com/nikhilsinghbisht/CodeSync-.git ~/CodeSync
          pip3 install -r ~/CodeSync/requirements.txt
          nohup python3 ~/CodeSync/app.py &
